version: "3.8"
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    image: wordpress
    volumes:
      - wordpress_data:/var/www/html
    expose:
      - "9000"
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/.
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    restart: on-failure

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception_network:
