services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "coffe"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: andre-da
      MYSQL_PASSWORD: "coffe"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./requirements/mariadb/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: andre-da
      WORDPRESS_DB_PASSWORD: "coffe"
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception_network

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx
      - ./requirements/nginx/certs:/etc/nginx/certs
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network

volumes:
  wordpress_data:
  mariadb_data:

networks:
  inception_network:

